### ISSUE TITLE
Password saver

### ISSUE THREAD

**Issue by Prodigy4532** [BGMP/DOC#1]
You should add a Password saver :D

**Comment by BGMP** [comment]
Will try and add it as soon as I can.

**Comment by BGMP** [comment]
I've tried a few hacky methods to implement this feature, yet it seems to me that it'd be a pain to actually find a way to do it with 0 dependencies, which is what i'm aiming for with this project. Therefore, I'm afraid I won't be adding this :(. Thanks for sharing it and please comment or make a new issue over any other ideas you may have eventually.
